[phases.setup]
cmds = [
  "corepack enable",
  "yarn set version stable"
]

[phases.install]
cmds = [
  "yarn install --frozen-lockfile"
]

[phases.build]
cmds = [
  "yarn build:railway"
]

[start]
cmd = "yarn start"
